# Generated by Django 6.0.7 on 2026-07-14 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0002_longitude_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchiprofil',
            name='vaqt_boshlanishi',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchiprofil',
            name='vaqt_yakuni',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Tugash vaqti'),
        ),
    ]
